name: circular_progress_bar_with_lines
description: Simple configurable circular progress bar built out of the lines.
version: 0.0.5
homepage: https://github.com/G33kFreak/circular_progress_bar_with_lines
repository: https://github.com/G33kFreak/circular_progress_bar_with_lines

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
